// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentAPI.Repository;

namespace PaymentAPI.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("PaymentAPI.Models.Entity.Produto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("VendaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("VendaID");

                    b.ToTable("TB_Produto");
                });

            modelBuilder.Entity("PaymentAPI.Models.Entity.Venda", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("StatusVenda")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("VendedorID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("VendedorID");

                    b.ToTable("TB_Venda");
                });

            modelBuilder.Entity("PaymentAPI.Models.Entity.Vendedor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("TB_Vendedor");
                });

            modelBuilder.Entity("PaymentAPI.Models.Entity.Produto", b =>
                {
                    b.HasOne("PaymentAPI.Models.Entity.Venda", null)
                        .WithMany("Produtos")
                        .HasForeignKey("VendaID");
                });

            modelBuilder.Entity("PaymentAPI.Models.Entity.Venda", b =>
                {
                    b.HasOne("PaymentAPI.Models.Entity.Vendedor", "Vendedor")
                        .WithMany()
                        .HasForeignKey("VendedorID");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("PaymentAPI.Models.Entity.Venda", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
